### ISSUE TITLE
jsの関数を切り分けたい

### ISSUE THREAD

**Issue by ishimaruco** [ishimaruco/play_roulette#1]
### 概要
* 現状の`index.js`は1つのfunctionにすべての処理を書いてしまっている

### やりたいこと
* 3つの処理に分けたい
  * arrayに行きたい場所をぶち込む処理
  * スタートボタンを押したときの処理
  * ストップボタンを押したときの処理

**Comment by tunagohan** [comment]
即時関数をメイン関数として扱い定義関数を呼び出せば解決するかもです。
ご存知かもしれませんが

定義関数はメソッドを**定義し**、**呼び出し**をしなければ実行されません。

```
function test() {
  alert("test");
}
```
を呼び出し実行するには
```
function test() {
  alert("test");
}

test();
```
とする必要があります。

即時関数の場合は

定義され呼び出し後実行されます
それが
```
(function test() {
  alert("test");
})();
```
になります。

やっていることは同じです。

では全部同じ即時関数で書けば良いやないか。
と思うはずです。

即時関数は、使い捨て関数みたいなイメージを持っていただくと分かりやすいです。

そいつが定義され呼び出しされ実行されると、役目を終えるため破棄されます。（厳密には違う）
ので後から呼び出すことができなくなってしまいます。
